# Generated by Django 6.1 on 2026-09-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_genre_delete_genres_alter_actor_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='biofraphy',
            new_name='biography',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.genre'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.director'),
        ),
        migrations.AlterField(
            model_name='review',
            name='film',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
