# Generated by Django 6.1 on 2026-09-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_biofraphy_director_biography_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.FloatField(verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(related_name='films', to='films.director'),
        ),
    ]
