# Generated by Django 6.1 on 2026-09-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_film_director_alter_film_rating_film_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='director',
            new_name='directors',
        ),
    ]
